services:
  api-server:
    build: ./api-server
    container_name: api-server
    ports:
      - "3000:3000"
    env_file:
      - ./api-server/.env
    volumes:
      - ./api-server/credentials.txt:/app/credentials.txt

  selenium-hub:
    image: seleniarm/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome-node:
    image: seleniarm/node-chromium:latest
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4 
    shm_size: '2gb'

  selenium-tests:
    build: ./selenium-tests
    container_name: selenium-tests
    depends_on:
      - api-server
      - selenium-hub
      - chrome-node
    environment:
      BASE_API_URL: http://api-server:3000
      BROWSER: grid-chrome
      GRID_URL: http://selenium-hub:4444/wd/hub
    volumes:
      - ./reports:/selenium-tests/target
